// This file is auto-generated by Payload when you run `npm run build` or `next dev`.
// It maps custom component paths to their actual implementations.
// For a config with no custom React components (fields/views/cells),
// an empty object is valid — Payload will use its built-in defaults.

import type { ImportMap } from 'payload'

export const importMap: ImportMap = {}
